monitor=,preferred,auto,1
exec-once=dbus-launch --sh-syntax

input {
    kb_layout=us
    follow_mouse=1
}

windowrulev2=float,class:^(pavucontrol)$
windowrulev2=noop,class:^(steam)$

bind=MOD, Q, exit
bind=MOD, C, exec, kitty
bind=MOD, V, togglefloating
bind=MOD, 1, workspace, 1
bind=MOD, 2, workspace, 2
bind=MOD, 3, workspace, 3
bind=MOD, 4, workspace, 4
bind=MOD, 5, workspace, 5
