bind=alt, f4, killactive
bind=super, return, exec, $terminal
bind=super, space, togglefloating
bind=super, 1, workspace, 1
bind=super, 2, workspace, 2
bind=super, 3, workspace, 3
bind=super, 4, workspace, 4
bind=super, 5, workspace, 5
bind=super, 6, workspace, 6
bind=super, 7, workspace, 7
bind=super, 8, workspace, 8
bind=super, 9, workspace, 9
bind=super, 0, workspace, 10

